### ISSUE TITLE
Adding engine="rda" to LIBNAME function, engine="Rdata" does not work for .rda files

### ISSUE THREAD

**Issue by Mia-data** [dbosak01/libr#131]
It is an ENHANCENT request rather than an issue but I have not idea how to change a label on Github (I am a newbe, any tips?).

To the point -  could you add "rda" value to engine argument of the libname function, please?  I mean: 
libname(name, directory_path, engine="rda")
Theare are multiple extension of the same file such as: rda, RDA, Rdata. It would be great if the engine argument could accept all of them (handling case sensitity).

I tried to use engine="Rdata" to load my rda files but it didn't work. It doesn't see any items. 
Thank you in advance! {libr} is an awesome package taht wouls help a lot in my projects.

**Comment by dbosak01** [comment]
Thanks for your feedback. It is a simple change.  I'll put this in the next release.

**Comment by Mia-data** [comment]
Awesome! Thank you

**Comment by dbosak01** [comment]
This is done and will be on CRAN by Sept 10th.  In the meantime, you can download from GitHub.

devtools::install_github('https://github.com/dbosak01/libr')
