### ISSUE TITLE
Format issues for date and datetime variables reading from SAS dataset

### ISSUE THREAD

**Issue by Raphael0522** [dbosak01/libr#157]
The SAS formats are missing when we use libname to read SAS data. For example, a variable with date format is converting to a numeric one. In addition, the converted number is not the same as the one in the origin SAS dataset. For example, '2019-08-14' is converted to 18122 by using libname function, however, it's actually 21775 when we remove the format in SAS dataset.

**Comment by dbosak01** [comment]
Hi Raphael!  Does the same thing happen when you use haven directly?

**Comment by Raphael0522** [comment]
Hi David, the date and datetime format look good if I use haven package to read dataset directly. Please use the attached 'testfile.sas7bdat' to test.
[testfile.zip](https://github.com/dbosak01/libr/files/14188716/testfile.zip)

**Comment by dbosak01** [comment]
Hmm... you're right.  It looks like the numeric value is the same as haven, but it is losing the Date data type.  I'll have to dig into this.  Give me a couple days.

**Comment by dbosak01** [comment]
I appears this bug was there a long time.  Thanks for noticing.  Fixed now.  Probably push to CRAN today.
