### ISSUE TITLE
Temporarily make `nanoparquet` optional to unbreak Big-endian builds

### ISSUE THREAD

**Issue by barracuda156** [dbosak01/libr#175]
Is it possible to move `nanoparquet` to suggested deps from required? It does not really work on Big-endian platforms at the moment, though upstream considers fixing it. See: https://github.com/r-lib/nanoparquet/issues/21

**Comment by dbosak01** [comment]
You're right.  I moved to suggests.  Rebuilt as version 1.3.8.  You can download from GitHub for now.  Will be another month until I can upload to CRAN.
