### ISSUE TITLE
Bizarre build error: `qs.sas7bdat: No space left on device`

### ISSUE THREAD

**Issue by barracuda156** [dbosak01/libr#176]
```
--->  Extracting libr_1.3.8.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-libr/R-libr/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/R-libr/libr_1.3.8.tar.gz' | /usr/bin/gnutar --no-same-owner -xf - 
--->  Configuring R-libr
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-libr/R-libr/work/libr" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
* checking for file ‘./DESCRIPTION’ ... OK
cp: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-libr/R-libr/work/.tmp/RtmpzUrobL/Rbuild107152c0db797/libr/tests/testthat/data/SDTM/qs.sas7bdat: No space left on device
 ERROR
copying to build directory failed
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-libr/R-libr/work/libr" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
Exit code: 1
```

How much space does it need? Admittedly, I have only 3+ GB right now, but this is a tiny R package, why does it want more than a GCC build? :)

**Comment by dbosak01** [comment]
Size of package is 3.549 GB.  Most of that is test data.  The test data is required for the unit tests, which are required for CRAN submission.  Overall, the size of the package has not changed in three versions.  The particular file referenced (qs.sas7bdat) is a test data file and is  2.5 mg.  I'm looking around a little and I'm not even sure it is being used.  I can do some more research to make sure it is not being used, and eliminate if possible.  Will still be another month until I can get on CRAN, as they only allow you to submit once per month.

**Comment by dbosak01** [comment]
Biggest is lb.sas7bdat, which is used for performance testing.  11MG.  Pondering how to eliminate.

**Comment by barracuda156** [comment]
It is perhaps not needed to modify CRAN version, but if a minimal version tarball can be provided via GitHub, for example, it will solve the issue. End-users perhaps do not need to run tests at a cost of downloading gigabytes of data (and those who need can run tests from within R session). I can disable test run in MacPorts in that case.

**Comment by dbosak01** [comment]
I reduced the package size by 1/3rd.  You can get from GitHub. Hopefully it will work better for you.

**Comment by barracuda156** [comment]
Thank you!
