### ISSUE TITLE
Question: Are there similitudes between this package and datapackage.r?

### ISSUE THREAD

**Issue by jmcastagnetto** [dbosak01/libr#80]
The people at frictionless data have this package https://frictionlessdata.github.io/datapackage-r/index.html, that seem to be aiming at the same problem space.

Are the data descriptions generated (schema and other metadata) compatible?

**Comment by dbosak01** [comment]
Jesus:

I hadn't seen this before, and I don't believe they are compatible.  I'm interested in what they are doing though, and will investigate more.  Thanks for mentioning this project.

David
