### ISSUE TITLE
Datastep Performance

### ISSUE THREAD

**Issue by dbosak01** [dbosak01/libr#86]
Will need to increase datastep performance even more at some point.  Not super urgent yet.  But want to put this on issue list.

**Comment by kaipingyang** [comment]
It's exciting to see your focus on improving data step performance.  I often use datastep() for some complex operations, and I look forward to using a high-performance version of datastep() as soon as possible.

**Comment by dbosak01** [comment]
Kaiping: I just started learning Rcpp for the purpose of improved performance.  Thanks for your comment.  I will prioritize this task.

**Comment by dbosak01** [comment]
Datastep about 40% faster.

**Comment by kaipingyang** [comment]
> Datastep about 40% faster.
Thank you for your work. I will enjoy it for data processing！

**Comment by dbosak01** [comment]
Will publish to CRAN in the next week or so.  In the meantime, you can pull down from GitHub if you want.
