### ISSUE TITLE
Option to silence column type output when importing

### ISSUE THREAD

**Issue by kputschko** [dbosak01/libr#88]
In readr, the read_* functions have a hidden option to silence import messages by setting the argument col_types = cols().  Could you make that available via libr::libname as well?

**Comment by dbosak01** [comment]
Sounds reasonable. Thanks for the suggestion.

**Comment by dbosak01** [comment]
Added _quiet_ parameter to libname() function to minimize output to console.  Really only does something on read_csv, as other file types weren't outputting anything anyway.  But may be a useful parameter in the future as more features become available.
